PKG_NAME="mergerfs"
PKG_VERSION="2.33.5"
PKG_ARCH="any"
PKG_SITE="https://github.com/trapexit/mergerfs"
PKG_URL="${PKG_SITE}/releases/download/${PKG_VERSION}/${PKG_NAME}-${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain fuse"
PKG_SECTION="tools"
PKG_LONGDESC="a featureful union filesystem"
PKG_MAKE_OPTS_TARGET="XATTR_AVAILABLE=0"
PKG_MAKEINSTALL_OPTS_TARGET="PREFIX=/usr"
