#!/bin/sh

################################################################################
#      This file is part of LibreELEC - https://libreelec.tv
#      Copyright (C) 2017-present Team LibreELEC
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

SOURCEREMOTECONF=""
REMAP="no"

if [ -f /storage/.config/remote.conf ]; then
  SOURCEREMOTECONF="/storage/.config"
  REMAP="yes"
elif [ -f /flash/remote.conf ]; then
  SOURCEREMOTECONF="/flash"
  REMAP="yes"
elif [ -f /etc/amremote/remote.conf -a "$(cat /proc/device-tree/dvbfe/dtv_demod0 2>/dev/null)" = "Avl6211" ]; then
  SOURCEREMOTECONF="/etc/amremote"
elif ! grep -q /dev/system /proc/mounts ; then
  mount -o rw,remount /flash
  mkdir -p /tmp/system
  mount -o ro /dev/system /tmp/system
  for f in /tmp/system/etc/remote*.conf; do
    cp $f /flash
    SOURCEREMOTECONF="/flash"
  done
  for f in /tmp/system/remote*.conf; do
    cp $f /flash
    SOURCEREMOTECONF="/flash"
  done
  umount /tmp/system
  REMAP="yes"
fi

if [ -n "$SOURCEREMOTECONF" ]; then
  cp $SOURCEREMOTECONF/remote*.conf /tmp
  if [ "$REMAP" = "yes" ]; then
    sed -i 's/ 15[^0-9]*$/ 1/
            s/ 63[^0-9]*$/ 90/
            s/ 97[^0-9]*$/ 28/
            s/ 102[^0-9]*$/ 172/
            s/ 125[^0-9]*$/ 46/
            s/ 142[^0-9]*$/ 116/
            s/ 143[^0-9]*$/ 116/
            s/ 158[^0-9]*$/ 1/
            s/ 183[^0-9]*$/ 59/
            s/ 184[^0-9]*$/ 399/
            s/ 185[^0-9]*$/ 400/
            s/ 186[^0-9]*$/ 60/
            s/ 232[^0-9]*$/ 28/
            s/ 240[^0-9]*$/ 164/
            s/ 241[^0-9]*$/ 163/
            s/ 242[^0-9]*$/ 165/
            s/ 244[^0-9]*$/ 208/
            s/ 245[^0-9]*$/ 168/
            s/ 264[^0-9]*$/ 63/
            s/ 704[^0-9]*$/ 116/' /tmp/remote*.conf
  fi
  for f in /tmp/remote*.conf; do
    /usr/bin/remotecfg $f
  done
fi
