#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)

echo "getting sources..."
  svn checkout http://boblight.googlecode.com/svn/trunk/ boblightd-latest

echo "getting version..."
  cd boblightd-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf boblightd-$SVN_REV
  cp -R boblightd-latest boblightd-$SVN_REV

#echo "cleaning sources..."
  find boblightd-$SVN_REV -name ".svn" -exec rm -rf {} \; 2>/dev/null

echo "packing sources..."
  tar cvJf boblightd-$SVN_REV.tar.xz boblightd-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf boblightd-$SVN_REV
