#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#      Copyright (C) 2011-2011 Gregor Fuis (gujs@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

REV="10.0-Dharma"

echo "getting sources..."
  git clone -b Dharma https://github.com/opdenkamp/xbmc.git xbmc-pvr
  cd xbmc-pvr
  git checkout 10.0-Dharma-pvr

echo "getting version..."
  GIT_REV=`git log -n1 --format=%h`
  echo $GIT_REV

echo "exporting sources..."
  git checkout-index -a -f --prefix=../xbmc-pvr-$REV/
  cd ..
  echo "$GIT_REV" > xbmc-pvr-$REV/git.version

echo "seperating theme..."
  rm -rf xbmc-pvr-theme-Confluence-$REV
  mv xbmc-pvr-$REV/addons/skin.confluence xbmc-pvr-theme-Confluence-$REV

echo "cleaning sources..."
  rm -rf xbmc-pvr-$REV/visualisations
  rm -rf xbmc-pvr-$REV/lib/libSDL-*
  rm -rf xbmc-pvr-$REV/lib/libcurl-*
  rm -rf xbmc-pvr-$REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-pvr-$REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-pvr-$REV -name *.$i -exec rm -rf {} ";"
  done

  # bundled win32 binaries
  rm -r xbmc-pvr-$REV/xbmc/visualizations/XBMCProjectM/win32

echo "packing sources..."
  tar cvjf xbmc-pvr-$REV.tar.bz2 xbmc-pvr-$REV
  tar cvjf xbmc-pvr-theme-Confluence-$REV.tar.bz2 xbmc-pvr-theme-Confluence-$REV

# echo "remove temporary sourcedir..."
#  rm -rf xbmc-pvr-$REV
#  rm -rf xbmc-pvr-theme-Confluence-$REV
