#!/bin/sh

REV="10.0-Dharma"

echo "getting sources..."
  svn co http://xbmc.svn.sourceforge.net/svnroot/xbmc/tags/$REV xbmc-$REV

# echo "getting version..."
#   cd xbmc-dharma-latest
#     SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
#     echo $SVN_REV
#   cd ..

# echo "copying sources..."
#   rm -rf xbmc-10.0-Dharma
#   cp -R xbmc-dharma-latest xbmc-dharma-$SVN_REV
#   echo "$SVN_REV" > xbmc-dharma-$SVN_REV/svn.version

echo "cleaning sources..."
  find xbmc-$REV -name .svn -exec rm -rf {} ";"

echo "seperating theme..."
  rm -rf xbmc-theme-Confluence-$REV
  mv xbmc-$REV/addons/skin.confluence xbmc-theme-Confluence-$REV

echo "cleaning sources..."
  rm -rf xbmc-$REV/visualisations
  rm -rf xbmc-$REV/lib/libSDL-*
  rm -rf xbmc-$REV/lib/libcurl-*
  rm -rf xbmc-$REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-$REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-$REV -name *.$i -exec rm -rf {} ";"
  done

  # bundled win32 binaries
  rm -r xbmc-$REV/xbmc/visualizations/XBMCProjectM/win32

echo "packing sources..."
  tar cvjf xbmc-$REV.tar.bz2 xbmc-$REV
  tar cvjf xbmc-theme-Confluence-$REV.tar.bz2 xbmc-theme-Confluence-$REV

echo "remove temporary sourcedir..."
  rm -rf xbmc-$REV
  rm -rf xbmc-theme-Confluence-$REV
