#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d libx264.git ]; then
    git clone git://git.videolan.org/x264.git -b master libx264.git
  fi

  cd libx264.git
    git checkout 86b71982e131eaa70125f8d0e725fcade9c4c677
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf libx264-$GIT_REV
  cp -R libx264.git libx264-$GIT_REV

echo "cleaning sources..."
  rm -rf libx264-$GIT_REV/.git
  rm libx264-$GIT_REV/.gitignore

echo "packing sources..."
  tar cvJf libx264-$GIT_REV.tar.xz libx264-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf libx264-$GIT_REV
