#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)

echo "getting sources..."
  wget http://www.lonesock.net/files/soil.zip
  unzip soil.zip
  mv "Simple OpenGL Image Library" soil-1.16

echo "packing sources..."
  tar cvJf soil-1.16.tar.xz soil-1.16

echo "remove temporary sourcedir..."
  rm -rf soil-1.16
  rm -rf soil.zip
