#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d psp1.git ]; then
    git clone https://github.com/libretro/psp1.git -b master psp1.git
    cd psp1.git
    git submodule update --init
    cd ..
  fi

  cd psp1.git
    git pull
    git submodule foreach git pull origin master
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf psp1-$GIT_REV
  cp -R psp1.git psp1-$GIT_REV

echo "cleaning sources..."
  rm -rf psp1-$GIT_REV/.git
  rm psp1-$GIT_REV/.gitignore
  rm -rf psp1-$GIT_REV/native/.git
  rm -rf psp1-$GIT_REV/pspautotests/.git
  rm -rf psp1-$GIT_REV/lang/.git
  rm -rf psp1-$GIT_REV/ffmpeg/.git
  rm -rf psp1-$GIT_REV/dx9sdk/.git
  rm -rf psp1-$GIT_REV/redist/.git
  rm -rf psp1-$GIT_REV/ext/armips/.git

echo "packing sources..."
  tar cvJf psp1-$GIT_REV.tar.xz psp1-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf psp1-$GIT_REV
