#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

MKPKG_CURRENTPATH=$(pwd)
MKPKG_TMP="$MKPKG_CURRENTPATH/mkpkg-temp"

mkdir -p $MKPKG_TMP
cd $MKPKG_TMP

echo "deleteing old revisions..."
  ls $MKPKG_TMP | \
  while read I; do
    if [ -f "${I}" ] ; then
      case "${I}" in
        tvheadend.tar.bz2)  rm "${I}";;
      esac
    elif [ -d "${I}" ] ; then
      case "${I}" in
        tvheadend) rm -Rf "${I}";;
      esac
    fi
  done

echo "getting sources if needed (or update only)"
  if [ ! -d tvheadend ]; then
    git clone git://github.com/andoma/tvheadend.git tvheadend
  fi

echo "updateing revision..."
  cd tvheadend
    git pull
  cd $MKPKG_TMP

echo "getting version..."
  cd tvheadend
    REV=$(git rev-parse --short HEAD)
  cd $MKPKG_TMP
  
echo "packing sources..."
  tar cvjf tvheadend-$REV.tar.bz2 tvheadend

cd $MKPKG_CURRENTPATH