#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="vdr-plugin-streamdev"
PKG_REPO="git://projects.vdr-developer.org/vdr-plugin-streamdev.git"

echo "getting sources..."
  if [ ! -d $PKG_NAME.git ]; then
    git clone $PKG_REPO $PKG_NAME.git
  fi

  cd $PKG_NAME.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$GIT_REV
  cp -R $PKG_NAME.git $PKG_NAME-$GIT_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/.git

echo "packing sources..."
  tar cvJf $PKG_NAME-$GIT_REV.tar.xz $PKG_NAME-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$GIT_REV
