#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d xwiimote.git ]; then
    git clone git://github.com/dvdhrm/xwiimote.git xwiimote.git
  fi

  cd xwiimote.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf xwiimote-$GIT_REV
  cp -R xwiimote.git xwiimote-$GIT_REV

echo "cleaning sources..."
  rm -rf xwiimote-$GIT_REV/.git

echo "packing sources..."
  tar cvJf xwiimote-$GIT_REV.tar.xz xwiimote-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf xwiimote-$GIT_REV
