#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  svn co http://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/pvr-testing2 xbmc-pvr-latest

echo "getting version..."
  cd xbmc-pvr-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Rev: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf xbmc-pvr-$SVN_REV
  cp -R xbmc-pvr-latest xbmc-pvr-$SVN_REV
  echo "$SVN_REV" > xbmc-pvr-$SVN_REV/svn.version

echo "cleaning sources..."
  find xbmc-pvr-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "seperating theme..."
  rm -rf xbmc-pvr-theme-Confluence-$SVN_REV
  mv xbmc-pvr-$SVN_REV/addons/skin.confluence xbmc-pvr-theme-Confluence-$SVN_REV

echo "cleaning sources..."
  rm -rf xbmc-pvr-$SVN_REV/visualisations
  rm -rf xbmc-pvr-$SVN_REV/lib/libSDL-*
  rm -rf xbmc-pvr-$SVN_REV/lib/libcurl-*
  rm -rf xbmc-pvr-$SVN_REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-pvr-$SVN_REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-pvr-$SVN_REV -name *.$i -exec rm -rf {} ";"
  done

  # remove bundled libraries (including zlib and OSX), saves space and forces using external versions
  for i in cximage-6.0/zlib libid3tag/zlib zlib
  do
    rm -rf xbmc-pvr-$SVN_REV/xbmc/lib/$i
  done

  # bundled win32 binaries
  rm -r xbmc-pvr-$SVN_REV/xbmc/visualizations/XBMCProjectM/win32

  # remove various headers 
  rm xbmc-pvr-$SVN_REV/xbmc/FileSystem/zlib.h

echo "packing sources..."
  tar cvjf xbmc-pvr-$SVN_REV.tar.bz2 xbmc-pvr-$SVN_REV
  tar cvjf xbmc-pvr-theme-Confluence-$SVN_REV.tar.bz2 xbmc-pvr-theme-Confluence-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf xbmc-pvr-$SVN_REV
  rm -rf xbmc-pvr-theme-Confluence-$SVN_REV
