#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="xbmc"
PKG_VERSION=""
GIT_REPO="-b Gotham git://github.com/xbmc/xbmc.git"
DEST_DIR="$PKG_NAME"

echo "getting sources..."
  if [ ! -d $DEST_DIR-latest ]; then
    git clone $GIT_REPO $DEST_DIR-latest
  fi

  cd $DEST_DIR-latest
    git pull

    echo "getting version..."
      GIT_REV=`git log -n1 --format=%h`
      echo $GIT_REV
  cd ..

  if [ -z "$PKG_VERSION" ]; then
      PKG_VERSION="13-$GIT_REV"
  fi

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R $DEST_DIR-latest $PKG_NAME-$PKG_VERSION
  echo "$GIT_REV" > $PKG_NAME-$PKG_VERSION/VERSION

echo "cleaning sources..."
  rm -rf $PKG_NAME-$PKG_VERSION/.git

echo "seperating theme..."
  rm -rf $PKG_NAME-theme-Confluence-$PKG_VERSION
  mv $PKG_NAME-$PKG_VERSION/addons/skin.confluence $PKG_NAME-theme-Confluence-$PKG_VERSION

echo "cleaning sources..."
  rm -rf $PKG_NAME-$PKG_VERSION/visualisations
  rm -rf $PKG_NAME-$PKG_VERSION/lib/libSDL-*
  rm -rf $PKG_NAME-$PKG_VERSION/lib/libcurl-*

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf $PKG_NAME-$PKG_VERSION/tools/$i
  done

  for i in dll a lib so bat; do
    find $PKG_NAME-$PKG_VERSION -name *.$i -exec rm -rf {} ";"
  done

  # bundled win32 binaries
  rm -r $PKG_NAME-$PKG_VERSION/xbmc/visualizations/XBMCProjectM/win32

echo "packing sources..."
  tar cvJf $PKG_NAME-$PKG_VERSION.tar.xz $PKG_NAME-$PKG_VERSION
  tar cvJf $PKG_NAME-theme-Confluence-$PKG_VERSION.tar.xz $PKG_NAME-theme-Confluence-$PKG_VERSION

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$PKG_VERSION
  rm -rf $PKG_NAME-theme-Confluence-$PKG_VERSION
