#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  if [ ! -d rtmpdump.git ]; then
    git clone git://git.ffmpeg.org/rtmpdump rtmpdump.git
  fi

  cd rtmpdump.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf rtmpdump-$GIT_REV
  cp -R rtmpdump.git rtmpdump-$GIT_REV

echo "cleaning sources..."
  rm -rf rtmpdump-$GIT_REV/.git

echo "packing sources..."
  tar cvJf rtmpdump-$GIT_REV.tar.xz rtmpdump-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf rtmpdump-$GIT_REV
