#!/bin/sh

echo "getting sources..."
  svn co svn://coreboot.org/flashrom/trunk flashrom-latest

echo "getting version..."
  cd flashrom-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf flashrom-$SVN_REV
  cp -R flashrom-latest flashrom-$SVN_REV

echo "cleaning sources..."
  find flashrom-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "packing sources..."
  tar cvjf flashrom-$SVN_REV.tar.bz2 flashrom-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf flashrom-$SVN_REV
