#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

REV="10.0-Dharma"

echo "getting sources..."
  svn co http://xbmc.svn.sourceforge.net/svnroot/xbmc/tags/$REV xbmc-$REV

echo "getting version..."
  cd xbmc-$REV
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Rev: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  echo "$SVN_REV" > xbmc-$REV/svn.version

echo "cleaning sources..."
  find xbmc-$REV -name .svn -exec rm -rf {} ";"

echo "seperating theme..."
  rm -rf xbmc-theme-Confluence-$REV
  mv xbmc-$REV/addons/skin.confluence xbmc-theme-Confluence-$REV

echo "cleaning sources..."
  rm -rf xbmc-$REV/visualisations
  rm -rf xbmc-$REV/lib/libSDL-*
  rm -rf xbmc-$REV/lib/libcurl-*
  rm -rf xbmc-$REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-$REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-$REV -name *.$i -exec rm -rf {} ";"
  done

  # bundled win32 binaries
  rm -r xbmc-$REV/xbmc/visualizations/XBMCProjectM/win32

echo "packing sources..."
  tar cvjf xbmc-$REV.tar.bz2 xbmc-$REV
  tar cvjf xbmc-theme-Confluence-$REV.tar.bz2 xbmc-theme-Confluence-$REV

# echo "remove temporary sourcedir..."
#  rm -rf xbmc-$REV
#  rm -rf xbmc-theme-Confluence-$REV
