#!/bin/sh

echo "getting sources..."
  svn co svn://svn.eglibc.org/branches/eglibc-2_11/libc eglibc-2.11-latest
  svn co svn://svn.eglibc.org/branches/eglibc-2_11/ports eglibc-2.11-latest/ports
  svn co svn://svn.eglibc.org/branches/eglibc-2_11/linuxthreads/linuxthreads eglibc-2.11-latest/linuxthreads
  svn co svn://svn.eglibc.org/branches/eglibc-2_11/linuxthreads/linuxthreads_db eglibc-2.11-latest/linuxthreads_db

echo "getting version..."
  cd eglibc-2.11-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf eglibc-2.11-$SVN_REV
  cp -R eglibc-2.11-latest eglibc-2.11-$SVN_REV

echo "cleaning sources..."
  find eglibc-2.11-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "packing sources..."
  tar cvjf eglibc-2.11-$SVN_REV.tar.bz2 eglibc-2.11-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf eglibc-2.11-$SVN_REV
