#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  
  if [ ! -f tornado-1.2.1.tar.gz ]; then
  	wget -O tornado-1.2.1.tar.gz https://github.com/downloads/facebook/tornado/tornado-1.2.1.tar.gz
  fi
  
  tar xzf tornado-1.2.1.tar.gz
	echo "renaming folder name..."
  mv tornado-1.2.1 tornado-ap-1.2.1
	echo "packing sources..."
  tar czf tornado-ap-1.2.1.tar.gz tornado-ap-1.2.1
  echo "remove temporary sourcedir..."
  rm -rf tornado-ap-1.2.1
