#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

echo "getting sources..."
  if [ ! -d lockdev.git ]; then
    git clone git://anonscm.debian.org/lockdev/lockdev.git -b master lockdev.git
  fi

  cd lockdev.git
    git pull
    GIT_REV=`git log -n1 --format=%H`
  cd ..

echo "copying sources..."
  rm -rf lockdev-$GIT_REV
  cp -R lockdev.git lockdev-$GIT_REV

echo "creating VERSION and other needed files"
  (
    cd lockdev-$GIT_REV
    LC_ALL=C ./scripts/git-version > VERSION
    touch ChangeLog
  ) 

echo "cleaning sources..."
  rm -rf lockdev-$GIT_REV/.git


echo "packing sources..."
  tar cvJf lockdev-$GIT_REV.tar.xz lockdev-$GIT_REV

echo "remove temporary sourcedir..."
  
