#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

if [ -z "$1" ]; then
  echo "Usage: $0 <branch-name>"
  exit 0
fi

echo "getting sources..."
  if [ ! -d kodi-language-addons.git ]; then
    git clone --depth=1 -b $1 https://github.com/xbmc/repo-resources.git kodi-language-addons.git
  fi

  cd kodi-language-addons.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf kodi-language-addons-$GIT_REV
  cp -R kodi-language-addons.git kodi-language-addons-$GIT_REV

echo "cleaning sources..."
  cd kodi-language-addons-$GIT_REV
    rm -rf .git
    ls | grep -v resource.language | xargs rm -r
  cd ..

echo "packing sources..."
  tar cvJf kodi-language-addons-$GIT_REV.tar.xz kodi-language-addons-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf kodi-language-addons-$GIT_REV
