#!/bin/sh

echo "getting sources..."
  svn co http://xbmc.svn.sourceforge.net/svnroot/xbmc/branches/pvr-testing2 xbmc-pvr-latest

echo "getting version..."
  cd xbmc-pvr-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf xbmc-pvr-$SVN_REV
  cp -R xbmc-pvr-latest xbmc-pvr-$SVN_REV

echo "cleaning sources..."
  find xbmc-pvr-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "seperating theme..."
  rm -rf xbmc-pvr-theme-Confluence-$SVN_REV
  mv xbmc-pvr-$SVN_REV/skin/Confluence xbmc-pvr-theme-Confluence-$SVN_REV

echo "cleaning sources..."
  rm -rf xbmc-pvr-$SVN_REV/visualizations/XBMCProjectM/win32
  rm -rf xbmc-pvr-$SVN_REV/lib/libSDL-*
  rm -rf xbmc-pvr-$SVN_REV/lib/libcurl-*
  rm -rf xbmc-pvr-$SVN_REV/skin
  rm -rf xbmc-pvr-$SVN_REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-pvr-$SVN_REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-pvr-$SVN_REV -name *.$i -exec rm -rf {} ";"
  done

echo "packing sources..."
  tar cvjf xbmc-pvr-$SVN_REV.tar.bz2 xbmc-pvr-$SVN_REV
  tar cvjf xbmc-pvr-theme-Confluence-$SVN_REV.tar.bz2 xbmc-pvr-theme-Confluence-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf xbmc-pvr-$SVN_REV
  rm -rf xbmc-pvr-theme-Confluence-$SVN_REV