#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d RTL8812AU.git ]; then
    git clone https://github.com/Grawp/rtl8812au_rtl8821au.git -b 4.3.22_beta RTL8812AU.git
  fi

  cd RTL8812AU.git
    git pull
    git checkout 928e27f2e0162ada76ba38a5efbba3a203273856
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf RTL8812AU-$GIT_REV
  cp -R RTL8812AU.git RTL8812AU-$GIT_REV

echo "cleaning sources..."
  rm -rf RTL8812AU-$GIT_REV/.git
  rm RTL8812AU-$GIT_REV/.gitignore

echo "packing sources..."
  tar cvJf RTL8812AU-$GIT_REV.tar.xz RTL8812AU-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf RTL8812AU-$GIT_REV
