#!/bin/sh

echo "getting sources..."
  svn checkout http://crystalhd-for-osx.googlecode.com/svn/trunk/crystalhd crystalhd-latest

echo "getting version..."
  cd crystalhd-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf crystalhd-$SVN_REV
  cp -R crystalhd-latest crystalhd-$SVN_REV

echo "cleaning sources..."
  find crystalhd-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "packing sources..."
  tar cvjf crystalhd-$SVN_REV.tar.bz2 crystalhd-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf crystalhd-$SVN_REV
