#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."

  if [ ! -f AF9035_2.6.38.tar.bz2 ]; then
    wget -O AF9035_2.6.38.tar.bz2 http://xgazza.altervista.org/Linux/DVB/Drivers/AF9035_2.6.38.tar.bz2
  fi

  tar xjf AF9035_2.6.38.tar.bz2
  echo "renaming folder name..."
  mv AF9035_2.6.38 AF9035_2.6.38-1.0
  echo "packing sources..."
  tar czf AF9035_2.6.38-1.0.tar.gz AF9035_2.6.38-1.0
  echo "remove temporary sourcedir..."
  rm -rf AF9035_2.6.38-1.0
