#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d bcm2835-driver.git ]; then
    git clone git://github.com/raspberrypi/firmware.git --depth=1 -b master bcm2835-driver.git
  fi

  cd bcm2835-driver.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf bcm2835-driver-$GIT_REV
  cp -R bcm2835-driver.git bcm2835-driver-$GIT_REV

  rm -rf bcm2835-bootloader-$GIT_REV
  cp -R bcm2835-driver.git/boot bcm2835-bootloader-$GIT_REV

echo "cleaning sources..."
  rm -rf bcm2835-driver-$GIT_REV/.git
  mkdir bcm2835-driver-$GIT_REV/softfp
  mv bcm2835-driver-$GIT_REV/opt bcm2835-driver-$GIT_REV/softfp
  rm -rf bcm2835-driver-$GIT_REV/*/opt/vc/src
  rm -rf bcm2835-driver-$GIT_REV/debug
  rm -rf bcm2835-driver-$GIT_REV/extra
  rm -rf bcm2835-driver-$GIT_REV/modules
  rm -rf bcm2835-driver-$GIT_REV/cutdown
  rm -rf bcm2835-driver-$GIT_REV/boot

  chmod 644 bcm2835-driver-$GIT_REV/*/opt/vc/include/bcm_host.h

  rm -rf bcm2835-bootloader-$GIT_REV/kernel*.img

echo "packing sources..."
  tar cvJf bcm2835-driver-$GIT_REV.tar.xz bcm2835-driver-$GIT_REV
  tar cvJf bcm2835-bootloader-$GIT_REV.tar.xz bcm2835-bootloader-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf bcm2835-driver-$GIT_REV
  rm -rf bcm2835-bootloader-$GIT_REV
