#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="xbmc-pvr"
GIT_REPO="-b Eden-pvr git://github.com/opdenkamp/xbmc.git"
DEST_DIR="$PKG_NAME"

echo "getting sources..."
  if [ ! -d $DEST_DIR-eden-latest ]; then
    git clone $GIT_REPO $DEST_DIR-eden-latest
  fi

  cd $DEST_DIR-eden-latest
    git pull

echo "getting version..."
  GIT_REV=`git log -n1 --format=%h`
  echo $GIT_REV
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$GIT_REV
  cp -R $DEST_DIR-eden-latest $PKG_NAME-$GIT_REV
  echo "$GIT_REV" > $PKG_NAME-$GIT_REV/git.version

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/.git

echo "seperating theme..."
  rm -rf $PKG_NAME-theme-Confluence-$GIT_REV
  mv $PKG_NAME-$GIT_REV/addons/skin.confluence $PKG_NAME-theme-Confluence-$GIT_REV
#  rm -rf $PKG_NAME-theme-Touched-$GIT_REV
#  mv $PKG_NAME-$GIT_REV/addons/skin.touched $PKG_NAME-theme-Touched-$GIT_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/visualisations
  rm -rf $PKG_NAME-$GIT_REV/lib/libSDL-*
  rm -rf $PKG_NAME-$GIT_REV/lib/libcurl-*
  rm -rf $PKG_NAME-$GIT_REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf $PKG_NAME-$GIT_REV/tools/$i
  done

  for i in dll a lib so bat; do
    find $PKG_NAME-$GIT_REV -name *.$i -exec rm -rf {} ";"
  done

  # bundled win32 binaries
  rm -r $PKG_NAME-$GIT_REV/xbmc/visualizations/XBMCProjectM/win32

echo "packing sources..."
  tar cvJf $PKG_NAME-$GIT_REV.tar.xz $PKG_NAME-$GIT_REV
  tar cvJf $PKG_NAME-theme-Confluence-$GIT_REV.tar.xz $PKG_NAME-theme-Confluence-$GIT_REV
#  tar cvJf $PKG_NAME-theme-Touched-$GIT_REV.tar.xz $PKG_NAME-theme-Touched-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$GIT_REV
  rm -rf $PKG_NAME-theme-Confluence-$GIT_REV
#  rm -rf $PKG_NAME-theme-Touched-$GIT_REV
