#!/bin/sh

echo "getting sources..."
  svn co http://xbmc.svn.sourceforge.net/svnroot/xbmc/trunk xbmc-latest

echo "getting version..."
  cd xbmc-latest
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf xbmc-$SVN_REV
  cp -R xbmc-latest xbmc-$SVN_REV
  echo "$SVN_REV" > xbmc-$SVN_REV/svn.version

echo "cleaning sources..."
  find xbmc-$SVN_REV -name .svn -exec rm -rf {} ";"

echo "seperating theme..."
  rm -rf xbmc-theme-Confluence-$SVN_REV
  mv xbmc-$SVN_REV/addons/skin.confluence xbmc-theme-Confluence-$SVN_REV

echo "cleaning sources..."
  rm -rf xbmc-$SVN_REV/visualisations
  rm -rf xbmc-$SVN_REV/lib/libSDL-*
  rm -rf xbmc-$SVN_REV/lib/libcurl-*
  rm -rf xbmc-$SVN_REV/project

  for i in "Changelog" "Fake\ Episode\ Maker" "MingwBuildEnvironment" \
           "PackageMaker" "Translator" "XBMCLive" "XprPack" \
           "HardwareConfigure" "Mach5" "osx" "UpdateThumbs.py" "XBMCTex"; do
    rm -rf xbmc-$SVN_REV/tools/$i
  done

  for i in dll a lib so bat; do
    find xbmc-$SVN_REV -name *.$i -exec rm -rf {} ";"
  done

  # remove bundled libraries (including zlib and OSX), saves space and forces using external versions
  for i in cximage-6.0/zlib libid3tag/zlib zlib
  do
    rm -rf xbmc-$SVN_REV/xbmc/lib/$i
  done

  # bundled win32 binaries
  rm -r xbmc-$SVN_REV/xbmc/visualizations/XBMCProjectM/win32

  # remove various headers 
  rm xbmc-$SVN_REV/xbmc/FileSystem/zlib.h

echo "packing sources..."
  tar cvjf xbmc-$SVN_REV.tar.bz2 xbmc-$SVN_REV
  tar cvjf xbmc-theme-Confluence-$SVN_REV.tar.bz2 xbmc-theme-Confluence-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf xbmc-$SVN_REV
  rm -rf xbmc-theme-Confluence-$SVN_REV
