#!/bin/sh
################################################################################
#      This file is part of LibreELEC - https://libreelec.tv
#      Copyright (C) 2009-2016 Lukas Rusak (lrusak@libreelec.tv)
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  if [ ! -d hyperion.git ]; then
    git clone --depth 1 --recursive https://github.com/tvdzwan/hyperion hyperion.git
  fi

  cd hyperion.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf hyperion-$GIT_REV
  cp -R hyperion.git hyperion-$GIT_REV

echo "cleaning sources..."
  rm -rf hyperion-$GIT_REV/.git

echo "packing sources..."
  tar cvJf hyperion-$GIT_REV.tar.xz hyperion-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf hyperion-$GIT_REV
