#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

date=$(date +%Y%m%d)
sundtek_base=sundtek-$date

rm -f installer.tar.gz
rm -fr $sundtek_base

echo "getting 32bit driver..."
wget --passive-ftp --no-check-certificate -O installer.tar.gz http://sundtek.de/media/netinst/32bit/installer.tar.gz
echo "unpacking..."
mkdir -p $sundtek_base
tar xzf installer.tar.gz -C $sundtek_base
chmod 755 $sundtek_base/opt/bin/*
echo "packing..."
tar czf $sundtek_base-i386.tar.gz $sundtek_base
rm -fr $sundtek_base

echo "getting 64bit driver..."
wget --passive-ftp --no-check-certificate -O installer.tar.gz http://sundtek.de/media/netinst/64bit/installer.tar.gz
echo "unpacking..."
mkdir -p $sundtek_base
tar xzf installer.tar.gz -C $sundtek_base
rm -f installer.tar.gz
chmod 755 $sundtek_base/opt/bin/*
echo "packing..."
tar czf $sundtek_base-x86_64.tar.gz $sundtek_base
rm -fr $sundtek_base

echo "getting armsysvhf driver..."
wget --passive-ftp --no-check-certificate -O installer.tar.gz http://sundtek.de/media/netinst/armsysvhf/installer.tar.gz
echo "unpacking..."
mkdir -p $sundtek_base
tar xzf installer.tar.gz -C $sundtek_base
rm -f installer.tar.gz
chmod 755 $sundtek_base/opt/bin/*
echo "packing..."
tar czf $sundtek_base-arm.tar.gz $sundtek_base
rm -fr $sundtek_base

