#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

echo "getting sources..."
  if [ ! -d bcm2835-driver.git ]; then
    git clone git://github.com/raspberrypi/firmware.git --depth=1 -b master bcm2835-driver.git
  fi

  cd bcm2835-driver.git
    git pull
    GIT_REV=`git log -n1 --format=%H`
  cd ..

echo "copying sources..."
  rm -rf bcm2835-driver-$GIT_REV
  cp -R bcm2835-driver.git bcm2835-driver-$GIT_REV

  rm -rf bcm2835-bootloader-$GIT_REV
  cp -R bcm2835-driver.git/boot bcm2835-bootloader-$GIT_REV

echo "cleaning sources..."
  rm -rf bcm2835-driver-$GIT_REV/.git
  mkdir bcm2835-driver-$GIT_REV/softfp
  mv bcm2835-driver-$GIT_REV/opt bcm2835-driver-$GIT_REV/softfp
  rm -rf bcm2835-driver-$GIT_REV/*/opt/vc/src
  rm -rf bcm2835-driver-$GIT_REV/debug
  rm -rf bcm2835-driver-$GIT_REV/extra
  rm -rf bcm2835-driver-$GIT_REV/modules
  rm -rf bcm2835-driver-$GIT_REV/cutdown
  rm -rf bcm2835-driver-$GIT_REV/boot

  chmod 644 bcm2835-driver-$GIT_REV/*/opt/vc/include/bcm_host.h

  rm -rf bcm2835-bootloader-$GIT_REV/kernel*.img

echo "packing sources..."
  tar cvJf bcm2835-driver-$GIT_REV.tar.xz bcm2835-driver-$GIT_REV
  tar cvJf bcm2835-bootloader-$GIT_REV.tar.xz bcm2835-bootloader-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf bcm2835-driver-$GIT_REV
  rm -rf bcm2835-bootloader-$GIT_REV
