#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  wget http://www.lonesock.net/files/soil.zip
  unzip soil.zip
  mv "Simple OpenGL Image Library" soil-1.16

echo "packing sources..."
  tar cvJf soil-1.16.tar.xz soil-1.16

echo "remove temporary sourcedir..."
  rm -rf soil-1.16
  rm -rf soil.zip
