[[protocols]]
name = "beelink_x2"
protocol = "NEC"
[protocols.scancodes]
0x804d = "KEY_MUTE"
0x8009 = "KEY_MEDIA"
0x8011 = "KEY_AUDIO"
0x8054 = "KEY_WWW"
0x804e = "KEY_VOLUMEUP"
0x80bb = "KEY_REWIND"
0x80bd = "KEY_FORWARD"
0x8056 = "KEY_VOLUMEDOWN"
0x8053 = "KEY_HOME"
0x801b = "KEY_BACK"
0x8026 = "KEY_UP"
0x8025 = "KEY_LEFT"
0x800d = "KEY_OK"
0x8027 = "KEY_RIGHT"
0x8028 = "KEY_DOWN"
0x8049 = "KEY_MENU"
0x8030 = "KEY_NUMERIC_0"
0x8031 = "KEY_NUMERIC_1"
0x8032 = "KEY_NUMERIC_2"
0x8033 = "KEY_NUMERIC_3"
0x8034 = "KEY_NUMERIC_4"
0x8035 = "KEY_NUMERIC_5"
0x8036 = "KEY_NUMERIC_6"
0x8037 = "KEY_NUMERIC_7"
0x8038 = "KEY_NUMERIC_8"
0x8039 = "KEY_NUMERIC_9"
0x8044 = "KEY_BACKSPACE"
0x8051 = "KEY_POWER"
