[[protocols]]
name = "Minix Neo"
protocol = "nec"
[protocols.scancodes]
0x118 = "KEY_POWER"
0x146 = "KEY_UP"
0x116 = "KEY_DOWN"
0x147 = "KEY_LEFT"
0x115 = "KEY_RIGHT"
0x155 = "KEY_ENTER"
0x110 = "KEY_VOLUMEDOWN"
0x140 = "KEY_BACK"
0x114 = "KEY_VOLUMEUP"
0x10d = "KEY_HOMEPAGE"
0x104 = "KEY_MENU"
0x112 = "KEY_CONFIG"
