[[protocols]]
name = "Xbox One"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x80d864 = "KEY_MEDIA"
0x80d820 = "KEY_LEFT"
0x80d821 = "KEY_RIGHT"
0x80d81e = "KEY_UP"
0x80d81f = "KEY_DOWN"
0x80d822 = "KEY_OK"
0x80d823 = "KEY_EXIT"
0x80d80e = "KEY_MUTE"
0x80d810 = "KEY_VOLUMEUP"
0x80d811 = "KEY_VOLUMEDOWN"
0x80d812 = "KEY_CHANNELUP"
0x80d813 = "KEY_CHANNELDOWN"
0x80d814 = "KEY_FASTFORWARD"
0x80d815 = "KEY_REWIND"
0x80d870 = "KEY_PLAYPAUSE"
0x80d819 = "KEY_STOP"
0x80d81a = "KEY_NEXT"
0x80d81b = "KEY_PREVIOUS"
0x80d826 = "KEY_INFO"
0x80d86f = "KEY_EPG"
0x80d86e = "KEY_ZOOM"
0x80d801 = "KEY_1"
0x80d802 = "KEY_2"
0x80d803 = "KEY_3"
0x80d804 = "KEY_4"
0x80d805 = "KEY_5"
0x80d806 = "KEY_6"
0x80d807 = "KEY_7"
0x80d808 = "KEY_8"
0x80d809 = "KEY_9"
0x80d800 = "KEY_0"
0x80d817 = "KEY_RECORD"
