#!/bin/sh

#Screen Init
echo 1 > /sys/class/graphics/fb0/blank;
echo 0 > /sys/class/graphics/fb0/state;
echo 0 > /sys/class/graphics/fb0/blank;

#Set up Schedutil

CPU_SCHEDUTIL_GOV=0

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors ]; \
	then
	read governors < \
		/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors

	case $governors in
		*schedutil*)
			 CPU_SCHEDUTIL_GOV=1
        ;;
    esac
fi

if [ $CPU_SCHEDUTIL_GOV -eq 1 ]; then
	for scaling_governor in \
		/sys/devices/system/cpu/cpu[0-7]/cpufreq/scaling_governor; do
		echo schedutil > $scaling_governor
	done
	if [ -e /sys/devices/system/cpu/cpufreq/schedutil/rate_limit_us ]; \
		then
		echo 2000 > \
			/sys/devices/system/cpu/cpufreq/schedutil/rate_limit_us
	fi
	if [ -e /sys/devices/system/cpu/cpufreq/schedutil/up_rate_limit_us ]; then
		echo 0 > /sys/devices/system/cpu/cpufreq/schedutil/up_rate_limit_us
	fi
	if [ -e /sys/devices/system/cpu/cpufreq/schedutil/down_rate_limit_us ]; then
		echo 500 > /sys/devices/system/cpu/cpufreq/schedutil/down_rate_limit_us
	fi
	if [ -e /sys/devices/system/cpu/cpufreq/schedutil/capacity_margin ]; then
		echo 1024 > /sys/devices/system/cpu/cpufreq/schedutil/capacity_margin
	fi
fi
