#!/bin/sh
#Screen Init
echo 4 > /sys/class/graphics/fb0/blank;
echo 0 > /sys/class/graphics/fb0/state;
echo 0 > /sys/class/graphics/fb0/blank;

#sysfs poke for reboot2payload
echo 1 > /sys/devices/r2p/default_payload_ready
