#!/bin/bash
# -*- tab-width: 4; sh-indentation: 4; sh-basic-offset: 4; indent-tabs-mode: t; -*-
#
# Copyright (c) 2016, NVIDIA CORPORATION.  All rights reserved.
#

#
# Wrap Android's "setprop" under L4T
#
prop="${1}"
value="${2}"

echo "${value}" > "/run/nvphs/properties/${prop}"

if [ $? != 0 ]; then
	echo >&2 "Warning: unable to write property '${prop}'"
	exit 1
fi
