#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

. config/options "${1}"

if [ -d "${PKG_BUILD}" -a "${PKG_SECTION}" != "virtual" ]; then
  print_color CLR_AUTOREMOVE "AUTOREMOVE ${PKG_BUILD}"
  echo
  rm -r "${PKG_BUILD}"
fi
