#!/bin/sh

. config/options

# Avoid infinite loop
[ "$*" = "$BUILD/configtools" ] && exit 0

$SCRIPTS/build configtools

for i in $@; do
  [ -f "$i/config.guess" ] && cp -f $BUILD/configtools/config.guess $i
  [ -f "$i/config.sub" ]   && cp -f $BUILD/configtools/config.sub   $i
  [ -f "$i/configure.guess" ] && cp -f $BUILD/configtools/config.guess $i/configure.guess
  [ -f "$i/configure.sub" ]   && cp -f $BUILD/configtools/config.sub   $i/configure.sub
done

exit 0
