#!/bin/sh

. config/options $1

for i in $@; do
  [ -f "$i/config.guess" ] && cp -f $SCRIPTS/configtools/config.guess $i
  [ -f "$i/config.sub" ]   && cp -f $SCRIPTS/configtools/config.sub   $i
  [ -f "$i/configure.guess" ] && cp -f $SCRIPTS/configtools/config.guess $i/configure.guess
  [ -f "$i/configure.sub" ]   && cp -f $SCRIPTS/configtools/config.sub   $i/configure.sub
done

exit 0
