#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

[ -d $BUILD/${PKG_NAME}[-_.]${PKG_VERSION} ] && PKG_BUILD=`ls -d $BUILD/${PKG_NAME}[-_.]${PKG_VERSION}`
[ -d $BUILD/${PKG_NAME}${PKG_VERSION} ] && PKG_BUILD=`ls -d $BUILD/${PKG_NAME}${PKG_VERSION}`

for i in `find $PKG_BUILD -name config.guess`; do
  CONFIGTOOLSDIR=`dirname $i`

  printf "%${INDENT}c FIXCONFIG   $1:   $CONFIGTOOLSDIR\n" >&$SILENT_OUT

  [ -f "$CONFIGTOOLSDIR/config.guess" ] && cp -f $SCRIPTS/configtools/config.guess $CONFIGTOOLSDIR
  [ -f "$CONFIGTOOLSDIR/config.sub" ] && cp -f $SCRIPTS/configtools/config.sub $CONFIGTOOLSDIR
  [ -f "$CONFIGTOOLSDIR/configure.guess" ] && cp -f $SCRIPTS/configtools/config.guess $CONFIGTOOLSDIR/configure.guess
  [ -f "$CONFIGTOOLSDIR/configure.sub" ] && cp -f $SCRIPTS/configtools/config.sub $CONFIGTOOLSDIR/configure.sub
done

exit 0
