#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)

. config/options $1

[ -f "$PKG_BUILD/VERSION" ] && PKG_GIT_VERSION=`cat $PKG_BUILD/VERSION`

echo $PKG_GIT_VERSION
