#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

$SCRIPTS/image_squashfs

get_version

RELEASE_DIR="target/$DISTRONAME-$TARGET_VERSION"

# cleanup
  rm -rf $RELEASE_DIR

# create release dir
  mkdir -p $RELEASE_DIR
    cp $ROOT/README $RELEASE_DIR
    cp $ROOT/CHANGELOG $RELEASE_DIR
  #  cp -R $CONFIG/image/* $RELEASE_DIR
    cp -R $CONFIG/release/* $RELEASE_DIR
    echo "$TARGET_VERSION" > $RELEASE_DIR/RELEASE

  mkdir -p $RELEASE_DIR/licenses
    cp $ROOT/licenses/* $RELEASE_DIR/licenses

  mkdir -p $RELEASE_DIR/target
    cp $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.system $RELEASE_DIR/target/SYSTEM
    cp $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.kernel $RELEASE_DIR/target/KERNEL

    if [ -f $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.mach_kernel ]; then
      cp $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.mach_kernel $RELEASE_DIR/target/MACH_KERNEL
    fi

# create md5sum's
  ( cd $RELEASE_DIR;
    md5sum -t target/SYSTEM > target/SYSTEM.md5;
    md5sum -t target/KERNEL > target/KERNEL.md5;
    if [ -f target/MACH_KERNEL ]; then
      md5sum -t target/MACH_KERNEL > target/MACH_KERNEL.md5;
    fi
  )

# create target directory
  mkdir -p $TARGET_IMG

# remove an previous created release tarball
  rm -rf $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.tar.bz2

# create release tarball
  tar cjf $TARGET_IMG/$DISTRONAME-$TARGET_VERSION.tar.bz2 -C target $DISTRONAME-$TARGET_VERSION

# cleanup release dir
  rm -rf $RELEASE_DIR
