#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2017-present Team LibreELEC (https://libreelec.tv)

. config/options $1

[ -n "$2" ] && PKG_ADDON_ID=$2

ADDON_DIRECTORY="$ADDON_BUILD/$PKG_ADDON_ID"

mkdir -p "$ADDON_DIRECTORY"

install_addon_files "$ADDON_DIRECTORY"

debug_strip "$ADDON_DIRECTORY"
