#!/bin/sh

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name"
  exit 1
fi

mkdir -p $INSTALLSTAMPS/$1
INSTALLSTAMP=$INSTALLSTAMPS/$1/install

if [ $1 = "image" ]; then
  rm -rf $INSTALLSTAMPS
  mkdir -p $INSTALLSTAMPS/image
fi

if [ ! -f $INSTALLSTAMP ]; then

  if [ -f $PKG_DIR/arch ]; then
    grep -q "$TARGET_ARCH" "$PKG_DIR/arch" || exit 0
    grep -q "\-$TARGET_ARCH" "$PKG_DIR/arch" && exit 0
  fi

  if [ -f $PKG_DIR/platform ]; then
    grep -q "$TARGET_PLATFORM" "$PKG_DIR/platform" || exit 0
    grep -q "\-$TARGET_PLATFORM" "$PKG_DIR/platform" && exit 0
  fi

  if [ -d $PKG_DIR/init.d ]; then
    mkdir -p $INSTALL/etc/init.d
    cp $PKG_DIR/init.d/* $INSTALL/etc/init.d/
  fi

  if [ -d $PKG_DIR/profile.d ]; then
    mkdir -p $INSTALL/etc/profile.d
    cp $PKG_DIR/profile.d/*.conf $INSTALL/etc/profile.d/
  fi

  if [ -d $PKG_DIR/init.network ]; then
    mkdir -p $INSTALL/etc/init.d/network
    cp $PKG_DIR/init.network/* $INSTALL/etc/init.d/network/
  fi

  $SCRIPTS/build $@
  printf  "%${INDENT}c INSTALL  $1\n" >&$SILENT_OUT
  #dialog --infobox "%${INDENT}c INSTALL  $1\n" 15 40
  export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

  for p in $PKG_DEPENDS; do
    $SCRIPTS/install $p
  done

  if [ -f $PKG_DIR/install ]; then
    $PKG_DIR/install $@ >&$VERBOSE_OUT
  fi

  touch $INSTALLSTAMP
fi
