#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

. config/options ""

while [ : ]; do
  echo "Waiting for build to start..."
  while [ : ]; do
    pid="$(cat "${THREAD_CONTROL}/pid" 2>/dev/null || true)"
    [ -n "${pid}" ] && ps -p ${pid} &>/dev/null && break
    sleep 1.0
  done

  tail -Fn+0 --pid=${pid} ${THREAD_CONTROL}/status 2>/dev/null

  echo
done
