#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020-2021 Ian Leonard (antonlacon@gmail.com)

# This performs an automated scan with corrections to the packages feed to
# follow certain coding standards used in the project. Corrections are grouped
# by the subdirectory within the packages feed, and then commited.

for directory in $(find packages/ -mindepth 1 -maxdepth 1 -type d | sort); do
  for file in $(find "${directory}" -type f -name "package.mk" | sort); do
    tools/fixlecode.py -qw -f "${file}"
  done
  git commit -qs -m "${directory##*/}: automated code cleanup" "${directory}"
done
