#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020-2021 Ian Leonard (antonlacon@gmail.com)

# This performs an automated scan with corrections to the packages feed to
# follow certain coding standards used in the project. Corrections are grouped
# by the subdirectory within the packages feed, and then commited.

# Corrections made:
# PKG_VAR="$PKG_VAR stuff" -> PKG_VAR+=" stuff"
# $PKG_VAR -> ${PKG_VAR}
# result=`subcommand` -> result=$(subcommand)
# [ test ] ; then -> [ test ]; then
# trailing whitespace at end of line

for directory in $(find packages/ -mindepth 1 -maxdepth 1 -type d | sort); do
  for file in $(find "${directory}" -type f -name "package.mk" | sort); do
    tools/fixlecode.py -qw -f "${file}"
    sed -i 's/[[:blank:]]*$//g' "${file}"
  done
  git commit -qs -m "${directory##*/}: automated code cleanup" "${directory}"
done
