#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021-present Team LibreELEC (https://libreelec.tv)

. config/options ""
. config/show_config

# Needed to obtain some CFLAGS/LDFLAGS
setup_toolchain target

show_config
