#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2015 Stephan Raue (stephan@openelec.tv)

# Enable io_is_busy for improved sdhost performance - essentially, equivalent of force_turbo=1 but for mmc
echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy

# Configure frequency scaling properties - should improve performance a little (turbo, in most cases)
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 100000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
