PKG_NAME="bindfs"
PKG_VERSION="9b15e7b9bfaaf0531fba0d3d07f57b6330222ba1"
PKG_ARCH="any"
PKG_SITE="https://github.com/mpartel/bindfs"
PKG_URL="${PKG_SITE}/archive/${PKG_VERSION}.tar.gz"
PKG_DEPENDS_TARGET="toolchain fuse"
PKG_SECTION="tools"
PKG_SHORTDESC="A FUSE filesystem thwt gives Advanced options for bind mounting"
PKG_MAKE_OPTS_TARGET="PREFIX=/usr"
PKG_TOOLCHAIN="autotools"
